

import type { Metadata } from "next";
import { Geist, Geist_Mono,Inter ,Poppins} from "next/font/google";
import "./globals.css";
import Header from "./components/header"
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({ subsets: ["latin"], weight: ["600"], variable: "--font-poppins" });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PNB Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
<Header />

{/* ✅ THIS IS REQUIRED for navigation to work */}
        <main>
          {children}
           <Footer />
        </main>
        

      </body>
    </html>
  );
}
